### ISSUE TITLE
Issue on rendering the PDF

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-user-guide#11]
When I use **manjaro-tools-pkg** to render the package with **buildpkg** I get the following error:

```
kpathsea: Running mktexpk --mfmode / --bdpi 600 --mag 2+44/600 --dpi 1244 pplrij8r
mktexpk: don't know how to create bitmap font for pplrij8r.
mktexpk: perhaps pplrij8r is missing from the map file.
kpathsea: Appending font creation commands to missfont.log.

!pdfTeX error: pdflatex (file pplrij8r): Font pplrij8r at 1244 not found
 ==> Fatal error occurred, no output PDF file produced!
```

**Comment by Pattedetable** [comment]
I run into the same problem when using **buildpkg**.  The LaTeX code compiles fine either from within Lyx or from the command line (without using buildpkg), but fails when using buildpkg.  I generally compile from within Lyx, which is why I did not notice this problem before.

**pplrij8r** is used for italics and belongs to the **Palatino** font, which is used as the roman font in the guide.  I looked at the commits made since March, and the font was not changed in any of them.  In fact, I don't remember ever changing it since I started contributing.

### Solutions and workarounds

1. By comparing my personal installation and the one I chroot into to compile the package, I noticed that out of the box, the new texlive installation does not seem to read any configuration file when updating the map file (you can check this by running `updmap-sys` or `updmap-user`).  However, after updating the map file while explicitly specifying a config file, the package compiles without a hitch.  Thus, a solution would be to add
`updmap-user --cnffile=/etc/texmf/web2c/updmap.cfg`
at the beginning of the **prepare()** block in the **PKGBUILD**.  After testing, package creation and installation work well, and the pdf displays as expected.
This problem may have appeared in a recent version of _texlive-core_ (since both _updmap_ and the map file containing _pplrij8r_ come from this package), although I could not tell which one at this point.  Fixing this would be the real solution.

2. Alternatively, changing the roman font to another one, such as _Times New Roman_, also solves the compilation error.  This could also be a possible workaround.

Do you have any preference?

**Comment by philmmanjaro** [comment]
We can go for the first. You're the artist. Decide.

**Comment by Pattedetable** [comment]
I also prefer the first option.  I'd go with this one.
